# Generated by Django 2.2.13 on 2020-06-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='aaa',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='aaaa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cccc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_cccc', to='home.CustomText'),
        ),
    ]
