# Generated by Django 2.2.13 on 2020-06-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200626_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='flot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='positv',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
